version: 0.2

env:
  variables:
    S3_BUCKET: "vee-24"
    APP_NAME: "vee"
    BUILD_ENV : "prod"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install Angular CLI
#      - yarn global add @angular/cli@6.0.8
      # Install node dependancies.
      - yarn global add @angular/cli
      - yarn install
#      - npm install -g @angular/cli
      - yarn add @angular-devkit/build-angular --dev
  build:
    commands:
      # Builds Angular application
      - echo Build started on `date`
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      # Clear S3 bucket.
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared. arn:aws:iam::315760622624:role/service-role/codebuild-vee-service-role
     # Copy dist folder to S3 bucket
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
